/**
 * Mapping of country/host names → ISO 3166-1 alpha-2 codes (lowercase).
 * Covers countries likely to appear as host nations in international
 * football match data, including historical entities.
 */

const COUNTRY_TO_CODE: Record<string, string> = {
  // UEFA
  England: "gb-eng",
  Scotland: "gb-sct",
  Wales: "gb-wls",
  "Northern Ireland": "gb-nir",
  France: "fr",
  Germany: "de",
  "West Germany": "de",
  Italy: "it",
  Spain: "es",
  Portugal: "pt",
  Netherlands: "nl",
  Holland: "nl",
  Belgium: "be",
  Switzerland: "ch",
  Sweden: "se",
  Norway: "no",
  Denmark: "dk",
  Finland: "fi",
  Iceland: "is",
  Russia: "ru",
  "Soviet Union": "ru",
  Ukraine: "ua",
  Poland: "pl",
  "Czech Republic": "cz",
  Czechoslovakia: "cz",
  Slovakia: "sk",
  Hungary: "hu",
  Romania: "ro",
  Bulgaria: "bg",
  Serbia: "rs",
  Yugoslavia: "rs",
  Croatia: "hr",
  "Bosnia and Herzegovina": "ba",
  Slovenia: "si",
  Montenegro: "me",
  "North Macedonia": "mk",
  Albania: "al",
  Greece: "gr",
  Turkey: "tr",
  Austria: "at",
  "Republic of Ireland": "ie",
  Ireland: "ie",
  Luxembourg: "lu",
  Malta: "mt",
  Cyprus: "cy",
  Estonia: "ee",
  Latvia: "lv",
  Lithuania: "lt",
  Belarus: "by",
  Moldova: "md",
  Georgia: "ge",
  Armenia: "am",
  Azerbaijan: "az",
  Kazakhstan: "kz",
  Israel: "il",
  "East Germany": "de",
  Saar: "de",
  // CONMEBOL
  Brazil: "br",
  Argentina: "ar",
  Uruguay: "uy",
  Paraguay: "py",
  Chile: "cl",
  Colombia: "co",
  Peru: "pe",
  Ecuador: "ec",
  Bolivia: "bo",
  Venezuela: "ve",
  // CONCACAF
  "United States": "us",
  USA: "us",
  Mexico: "mx",
  Canada: "ca",
  "Costa Rica": "cr",
  Honduras: "hn",
  "El Salvador": "sv",
  Guatemala: "gt",
  Panama: "pa",
  Jamaica: "jm",
  "Trinidad and Tobago": "tt",
  Trinidad: "tt",
  Haiti: "ht",
  Cuba: "cu",
  // CAF
  Nigeria: "ng",
  Ghana: "gh",
  "South Africa": "za",
  Egypt: "eg",
  Morocco: "ma",
  Tunisia: "tn",
  Algeria: "dz",
  Cameroon: "cm",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  Senegal: "sn",
  "DR Congo": "cd",
  Zambia: "zm",
  Zimbabwe: "zw",
  Kenya: "ke",
  Ethiopia: "et",
  Angola: "ao",
  Mali: "ml",
  "Burkina Faso": "bf",
  Togo: "tg",
  Benin: "bj",
  Niger: "ne",
  Chad: "td",
  Sudan: "sd",
  "South Sudan": "ss",
  Uganda: "ug",
  Tanzania: "tz",
  Mozambique: "mz",
  Madagascar: "mg",
  Malawi: "mw",
  Rwanda: "rw",
  Burundi: "bi",
  Somalia: "so",
  Mauritania: "mr",
  Gambia: "gm",
  Guinea: "gn",
  "Guinea-Bissau": "gw",
  "Sierra Leone": "sl",
  Liberia: "lr",
  "Cape Verde": "cv",
  "São Tomé and Príncipe": "st",
  "Equatorial Guinea": "gq",
  Gabon: "ga",
  "Republic of the Congo": "cg",
  "Central African Republic": "cf",
  Lesotho: "ls",
  Botswana: "bw",
  Namibia: "na",
  Eswatini: "sz",
  Comoros: "km",
  Mauritius: "mu",
  Seychelles: "sc",
  // AFC
  Japan: "jp",
  "South Korea": "kr",
  "Korea Republic": "kr",
  "North Korea": "kp",
  "Korea DPR": "kp",
  China: "cn",
  India: "in",
  Australia: "au",
  "Saudi Arabia": "sa",
  Iran: "ir",
  Iraq: "iq",
  Qatar: "qa",
  "United Arab Emirates": "ae",
  Oman: "om",
  Bahrain: "bh",
  Kuwait: "kw",
  Jordan: "jo",
  Lebanon: "lb",
  Syria: "sy",
  Yemen: "ye",
  Palestine: "ps",
  Uzbekistan: "uz",
  Turkmenistan: "tm",
  Kyrgyzstan: "kg",
  Tajikistan: "tj",
  Afghanistan: "af",
  Pakistan: "pk",
  Bangladesh: "bd",
  "Sri Lanka": "lk",
  Nepal: "np",
  Bhutan: "bt",
  Maldives: "mv",
  Malaysia: "my",
  Indonesia: "id",
  "Dutch East Indies": "id",
  Thailand: "th",
  Vietnam: "vn",
  Philippines: "ph",
  Singapore: "sg",
  Myanmar: "mm",
  Cambodia: "kh",
  Laos: "la",
  Mongolia: "mn",
  // OFC
  "New Zealand": "nz",
  Fiji: "fj",
  "Papua New Guinea": "pg",
  "Solomon Islands": "sb",
  Vanuatu: "vu",
  "New Caledonia": "nc",
  Tahiti: "pf",
  Samoa: "ws",
  "American Samoa": "as",
  Tonga: "to",
  "Cook Islands": "ck",
  // Other
  "Great Britain": "gb",
  UK: "gb",
  Britain: "gb",
  Zanzibar: "tz",
};

export function getCountryCode(countryName: string): string | null {
  return COUNTRY_TO_CODE[countryName] ?? null;
}

export const FLAG_BASE_URL = "/flags";
