/**
 * Mapping of country/host names → ISO 3166-1 alpha-2 codes (lowercase).
 * Covers countries likely to appear as host nations in international
 * football match data, including historical entities.
 */

const COUNTRY_TO_CODE: Record<string, string> = {
  // UEFA
  England: "gb-eng",
  Scotland: "gb-sct",
  Wales: "gb-wls",
  "Northern Ireland": "gb-nir",
  France: "fr",
  Germany: "de",
  "West Germany": "de",
  Italy: "it",
  Spain: "es",
  Portugal: "pt",
  Netherlands: "nl",
  Holland: "nl",
  Belgium: "be",
  Switzerland: "ch",
  Sweden: "se",
  Norway: "no",
  Denmark: "dk",
  Finland: "fi",
  Iceland: "is",
  Russia: "ru",
  "Soviet Union": "ru",
  Ukraine: "ua",
  Poland: "pl",
  "Czech Republic": "cz",
  Czechoslovakia: "cz",
  Slovakia: "sk",
  Hungary: "hu",
  Romania: "ro",
  Bulgaria: "bg",
  Serbia: "rs",
  Yugoslavia: "rs",
  Croatia: "hr",
  "Bosnia and Herzegovina": "ba",
  Slovenia: "si",
  Montenegro: "me",
  "North Macedonia": "mk",
  Albania: "al",
  Greece: "gr",
  Turkey: "tr",
  Austria: "at",
  "Republic of Ireland": "ie",
  Ireland: "ie",
  Luxembourg: "lu",
  Malta: "mt",
  Cyprus: "cy",
  Estonia: "ee",
  Latvia: "lv",
  Lithuania: "lt",
  Belarus: "by",
  Moldova: "md",
  Georgia: "ge",
  Armenia: "am",
  Azerbaijan: "az",
  Kazakhstan: "kz",
  Israel: "il",
  Andorra: "ad",
  "Faroe Islands": "fo",
  Gibraltar: "gi",
  Kosovo: "xk",
  Liechtenstein: "li",
  Monaco: "mc",
  "San Marino": "sm",
  "Vatican City": "va",
  "East Germany": "de",
  "German DR": "de",
  Saar: "de",
  Saarland: "de",
  Bohemia: "cz",
  "Bohemia and Moravia": "cz",
  // UEFA micro-states & dependencies
  Guernsey: "gg",
  Jersey: "je",
  "Isle of Man": "im",
  Åland: "ax",
  "Åland Islands": "ax",
  // CONMEBOL
  Brazil: "br",
  Argentina: "ar",
  Uruguay: "uy",
  Paraguay: "py",
  Chile: "cl",
  Colombia: "co",
  Peru: "pe",
  Ecuador: "ec",
  Bolivia: "bo",
  Venezuela: "ve",
  // CONCACAF
  "United States": "us",
  USA: "us",
  Mexico: "mx",
  Canada: "ca",
  "Costa Rica": "cr",
  Honduras: "hn",
  "El Salvador": "sv",
  Guatemala: "gt",
  Panama: "pa",
  Jamaica: "jm",
  "Trinidad and Tobago": "tt",
  Trinidad: "tt",
  Haiti: "ht",
  Cuba: "cu",
  // CONCACAF micro-states & dependencies
  Anguilla: "ai",
  "Antigua and Barbuda": "ag",
  Aruba: "aw",
  Bahamas: "bs",
  Barbados: "bb",
  Belize: "bz",
  Bermuda: "bm",
  Bonaire: "bq",
  "British Virgin Islands": "vg",
  "Cayman Islands": "ky",
  Curaçao: "cw",
  Dominica: "dm",
  "Dominican Republic": "do",
  Greenland: "gl",
  Grenada: "gd",
  Guadeloupe: "gp",
  Martinique: "mq",
  Montserrat: "ms",
  "Puerto Rico": "pr",
  "Saint Barthélemy": "bl",
  "Saint Kitts and Nevis": "kn",
  "Saint Lucia": "lc",
  "Saint Martin": "mf",
  "Saint Pierre and Miquelon": "pm",
  "Saint Vincent and the Grenadines": "vc",
  "Sint Maarten": "sx",
  "Turks and Caicos Islands": "tc",
  "United States Virgin Islands": "vi",
  // CAF
  Nigeria: "ng",
  Ghana: "gh",
  "South Africa": "za",
  Egypt: "eg",
  Morocco: "ma",
  Tunisia: "tn",
  Algeria: "dz",
  Cameroon: "cm",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  Senegal: "sn",
  "DR Congo": "cd",
  Zambia: "zm",
  Zimbabwe: "zw",
  Kenya: "ke",
  Ethiopia: "et",
  Angola: "ao",
  Mali: "ml",
  "Burkina Faso": "bf",
  Togo: "tg",
  Benin: "bj",
  Niger: "ne",
  Chad: "td",
  Sudan: "sd",
  "South Sudan": "ss",
  Uganda: "ug",
  Tanzania: "tz",
  Mozambique: "mz",
  Madagascar: "mg",
  Malawi: "mw",
  Rwanda: "rw",
  Burundi: "bi",
  Somalia: "so",
  Mauritania: "mr",
  Gambia: "gm",
  Guinea: "gn",
  "Guinea-Bissau": "gw",
  "Sierra Leone": "sl",
  Liberia: "lr",
  "Cape Verde": "cv",
  "São Tomé and Príncipe": "st",
  "Equatorial Guinea": "gq",
  Gabon: "ga",
  "Republic of the Congo": "cg",
  "Central African Republic": "cf",
  Lesotho: "ls",
  Botswana: "bw",
  Namibia: "na",
  Eswatini: "sz",
  Comoros: "km",
  Mauritius: "mu",
  Seychelles: "sc",
  // CAF micro-states & dependencies
  Djibouti: "dj",
  Eritrea: "er",
  Libya: "ly",
  Réunion: "re",
  Mayotte: "yt",
  "Saint Helena": "sh",
  Somaliland: "so",
  // AFC
  Japan: "jp",
  "South Korea": "kr",
  "Korea Republic": "kr",
  "North Korea": "kp",
  "Korea DPR": "kp",
  China: "cn",
  India: "in",
  Australia: "au",
  "Saudi Arabia": "sa",
  Iran: "ir",
  Iraq: "iq",
  Qatar: "qa",
  "United Arab Emirates": "ae",
  Oman: "om",
  Bahrain: "bh",
  Kuwait: "kw",
  Jordan: "jo",
  Lebanon: "lb",
  Syria: "sy",
  Yemen: "ye",
  Palestine: "ps",
  Uzbekistan: "uz",
  Turkmenistan: "tm",
  Kyrgyzstan: "kg",
  Tajikistan: "tj",
  Afghanistan: "af",
  Pakistan: "pk",
  Bangladesh: "bd",
  "Sri Lanka": "lk",
  Nepal: "np",
  Bhutan: "bt",
  Maldives: "mv",
  Malaysia: "my",
  Indonesia: "id",
  "Dutch East Indies": "id",
  Thailand: "th",
  Vietnam: "vn",
  Philippines: "ph",
  Singapore: "sg",
  Myanmar: "mm",
  Cambodia: "kh",
  Laos: "la",
  Mongolia: "mn",
  // AFC micro-states & dependencies
  Brunei: "bn",
  "Hong Kong": "hk",
  Macau: "mo",
  Taiwan: "tw",
  Timor: "tl",
  "Timor-Leste": "tl",
  Guam: "gu",
  "Northern Mariana Islands": "mp",
  "Marshall Islands": "mh",
  Micronesia: "fm",
  Palau: "pw",
  // OFC
  "New Zealand": "nz",
  Fiji: "fj",
  "Papua New Guinea": "pg",
  "Solomon Islands": "sb",
  Vanuatu: "vu",
  "New Caledonia": "nc",
  Tahiti: "pf",
  Samoa: "ws",
  "American Samoa": "as",
  Tonga: "to",
  "Cook Islands": "ck",
  // OFC micro-states
  Niue: "nu",
  Tuvalu: "tv",
  // Other
  "Great Britain": "gb",
  UK: "gb",
  Britain: "gb",
  Zanzibar: "tz",
  // Other micro-states & dependencies
  "French Guiana": "gf",
  Guyana: "gy",
  Suriname: "sr",
  Nicaragua: "ni",
  "Falkland Islands": "fk",
  Kiribati: "ki",
  "Western Sahara": "eh",
  "British Guiana": "gy",
  // Historical aliases
  "Vietnam Republic": "vn",
  "North Vietnam": "vn",
  Burma: "mm",
  Ceylon: "lk",
  Congo: "cg",
  "Congo-Kinshasa": "cd",
  "Belgian Congo": "cd",
  Dahomey: "bj",
  "Dutch Guyana": "sr",
  "French Somaliland": "dj",
  "Gold Coast": "gh",
  "Irish Free State": "ie",
  Malaya: "my",
  Manchuria: "cn",
  Manchukuo: "cn",
  "Mandatory Palestine": "ps",
  "New Hebrides": "vu",
  "Northern Rhodesia": "zm",
  Nyasaland: "mw",
  "Portuguese Guinea": "gw",
  "Serbia and Montenegro": "rs",
  "FR Yugoslavia": "rs",
  "Southern Rhodesia": "zw",
  Swaziland: "sz",
  Tanganyika: "tz",
  "United Arab Republic": "eg",
  "Upper Volta": "bf",
  "Western Samoa": "ws",
  "Yemen AR": "ye",
  "Yemen DPR": "ye",
  "South Yemen": "ye",
  Zaïre: "cd",
  Éire: "ie",
  // Non-ISO regional & historical flags (custom SVGs)
  "Abkhazia": "abkhazia",
  "Alderney": "alderney",
  "Andalusia": "andalusia",
  "Artsakh": "artsakh",
  "Asturias": "asturias",
  "Basque Country": "basque-country",
  "Biafra": "biafra",
  "Brittany": "brittany",
  "Canary Islands": "canary-islands",
  "Catalonia": "catalonia",
  "Chagos Islands": "chagos-islands",
  "Chechnya": "chechnya",
  "Corsica": "corsica",
  "Crimea": "crimea",
  "Darfur": "darfur",
  "Donetsk PR": "donetsk-pr",
  "East Turkestan": "east-turkestan",
  "Elba Island": "elba-island",
  "Galicia": "galicia",
  "Gotland": "gotland",
  "Gozo": "gozo",
  "Kabylia": "kabylia",
  "Kurdistan": "kurdistan",
  "Luhansk PR": "luhansk-pr",
  "Menorca": "menorca",
  "Northern Cyprus": "northern-cyprus",
  "Occitania": "occitania",
  "Orkney": "orkney",
  "Quebec": "quebec",
  "Rhodes": "rhodes",
  "Sápmi": "sapmi",
  "Shetland": "shetland",
  "Sicily": "sicily",
  "Silesia": "silesia",
  "South Ossetia": "south-ossetia",
  "Tamil Eelam": "tamil-eelam",
  "Tibet": "tibet",
  "West Papua": "west-papua",
  "Ambazonia": "ambazonia",
  "Arameans Suryoye": "arameans-suryoye",
  "Aymara": "aymara",
  "Barawa": "barawa",
  "Cascadia": "cascadia",
  "Central Spain": "central-spain",
  "Chameria": "chameria",
  "Cilento": "cilento",
  "County of Nice": "county-of-nice",
  "Délvidék": "delvidek",
  "Ellan Vannin": "ellan-vannin",
  "Felvidék": "felvidek",
  "Franconia": "franconia",
  "Frøya": "froya",
  "Găgăuzia": "gagauzia",
  "Hitra": "hitra",
  "Hmong": "hmong",
  "Iraqi Kurdistan": "iraqi-kurdistan",
  "Isle of Wight": "isle-of-wight",
  "Kernow": "kernow",
  "Kárpátalja": "karpatalja",
  "Madrid": "madrid",
  "Mapuche": "mapuche",
  "Matabeleland": "matabeleland",
  "Maule Sur": "maule-sur",
  "Padania": "padania",
  "Panjab": "panjab",
  "Parishes of Jersey": "parishes-of-jersey",
  "Provence": "provence",
  "Raetia": "raetia",
  "Republic of St. Pauli": "republic-of-st-pauli",
  "Romani people": "romani-people",
  "Ryūkyū": "ryukyu",
  "Saare County": "saare-county",
  "Sark": "sark",
  "Saugeais": "saugeais",
  "Sealand": "sealand",
  "Seborga": "seborga",
  "Surrey": "surrey",
  "Székely Land": "szekely-land",
  "Ticino": "ticino",
  "Two Sicilies": "two-sicilies",
  "United Koreans in Japan": "united-koreans-in-japan",
  "Wallis Islands and Futuna": "wallis-and-futuna",
  "Western Armenia": "western-armenia",
  "Western Australia": "western-australia",
  "Western Isles": "western-isles",
  "Ynys Môn": "ynys-mon",
  "Yorkshire": "yorkshire",
  "Yoruba Nation": "yoruba-nation",
};

export function getCountryCode(countryName: string): string | null {
  return COUNTRY_TO_CODE[countryName] ?? null;
}

/** Returns the set of all mapped country/team names (case-sensitive keys). */
export function getAllMappedNames(): Set<string> {
  return new Set(Object.keys(COUNTRY_TO_CODE));
}

export const FLAG_BASE_URL = "/flags";
